function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "stdtypesUsage"};
	this.sidHashMap["stdtypesUsage"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "stdtypesUsage:1"};
	this.sidHashMap["stdtypesUsage:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "stdtypesUsage:2"};
	this.sidHashMap["stdtypesUsage:2"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "stdtypesUsage:1"};
	this.sidHashMap["stdtypesUsage:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "stdtypesUsage:3"};
	this.sidHashMap["stdtypesUsage:3"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "stdtypesUsage:1:1"};
	this.sidHashMap["stdtypesUsage:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "stdtypesUsage:1:2"};
	this.sidHashMap["stdtypesUsage:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "stdtypesUsage:1:3"};
	this.sidHashMap["stdtypesUsage:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "stdtypesUsage:1:4"};
	this.sidHashMap["stdtypesUsage:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "stdtypesUsage:1:5"};
	this.sidHashMap["stdtypesUsage:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "stdtypesUsage:1:6"};
	this.sidHashMap["stdtypesUsage:1:6"] = {rtwname: "<S1>:6"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
