function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Session3_MBD_CalculatorGraficalFunction"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Session3_MBD_CalculatorGraficalFunction:1"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/In2"] = {sid: "Session3_MBD_CalculatorGraficalFunction:2"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:2"] = {rtwname: "<Root>/In2"};
	this.rtwnameHashMap["<Root>/Chart1"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3"] = {rtwname: "<Root>/Chart1"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "Session3_MBD_CalculatorGraficalFunction:4"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:4"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<Root>/Out2"] = {sid: "Session3_MBD_CalculatorGraficalFunction:5"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:5"] = {rtwname: "<Root>/Out2"};
	this.rtwnameHashMap["<Root>/Out3"] = {sid: "Session3_MBD_CalculatorGraficalFunction:6"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:6"] = {rtwname: "<Root>/Out3"};
	this.rtwnameHashMap["<Root>/Out4"] = {sid: "Session3_MBD_CalculatorGraficalFunction:7"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:7"] = {rtwname: "<Root>/Out4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:1"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:11"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:11"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:11"] = {rtwname: "<S1>:11"};
	this.rtwnameHashMap["<S1>:8"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:8"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:8"] = {rtwname: "<S1>:8"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:5"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:29"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:29"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:29"] = {rtwname: "<S1>:29"};
	this.rtwnameHashMap["<S1>:10"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:10"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:10"] = {rtwname: "<S1>:10"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:3"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:13"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:13"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:13"] = {rtwname: "<S1>:13"};
	this.rtwnameHashMap["<S1>:7"] = {sid: "Session3_MBD_CalculatorGraficalFunction:3:7"};
	this.sidHashMap["Session3_MBD_CalculatorGraficalFunction:3:7"] = {rtwname: "<S1>:7"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
