function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "session2_MBD_SubsystemCalcuator"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "session2_MBD_SubsystemCalcuator:3"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:3"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "session2_MBD_SubsystemCalcuator:1"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/In2"] = {sid: "session2_MBD_SubsystemCalcuator:2"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:2"] = {rtwname: "<Root>/In2"};
	this.rtwnameHashMap["<Root>/Subsystem1"] = {sid: "session2_MBD_SubsystemCalcuator:3"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:3"] = {rtwname: "<Root>/Subsystem1"};
	this.rtwnameHashMap["<Root>/out SUM"] = {sid: "session2_MBD_SubsystemCalcuator:14"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:14"] = {rtwname: "<Root>/out SUM"};
	this.rtwnameHashMap["<Root>/out SUB "] = {sid: "session2_MBD_SubsystemCalcuator:15"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:15"] = {rtwname: "<Root>/out SUB "};
	this.rtwnameHashMap["<Root>/out MUL "] = {sid: "session2_MBD_SubsystemCalcuator:16"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:16"] = {rtwname: "<Root>/out MUL "};
	this.rtwnameHashMap["<Root>/Out DIV "] = {sid: "session2_MBD_SubsystemCalcuator:17"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:17"] = {rtwname: "<Root>/Out DIV "};
	this.rtwnameHashMap["<S1>/In2"] = {sid: "session2_MBD_SubsystemCalcuator:4"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:4"] = {rtwname: "<S1>/In2"};
	this.rtwnameHashMap["<S1>/In3"] = {sid: "session2_MBD_SubsystemCalcuator:5"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:5"] = {rtwname: "<S1>/In3"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "session2_MBD_SubsystemCalcuator:6"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:6"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Divide"] = {sid: "session2_MBD_SubsystemCalcuator:7"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:7"] = {rtwname: "<S1>/Divide"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "session2_MBD_SubsystemCalcuator:8"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:8"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Subtract"] = {sid: "session2_MBD_SubsystemCalcuator:9"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:9"] = {rtwname: "<S1>/Subtract"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "session2_MBD_SubsystemCalcuator:10"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:10"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S1>/Out2"] = {sid: "session2_MBD_SubsystemCalcuator:11"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:11"] = {rtwname: "<S1>/Out2"};
	this.rtwnameHashMap["<S1>/Out3"] = {sid: "session2_MBD_SubsystemCalcuator:12"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:12"] = {rtwname: "<S1>/Out3"};
	this.rtwnameHashMap["<S1>/Out4"] = {sid: "session2_MBD_SubsystemCalcuator:13"};
	this.sidHashMap["session2_MBD_SubsystemCalcuator:13"] = {rtwname: "<S1>/Out4"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
