function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Session2_MBD_Factorial"};
	this.sidHashMap["Session2_MBD_Factorial"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Session2_MBD_Factorial:1"};
	this.sidHashMap["Session2_MBD_Factorial:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Session2_MBD_Factorial:32"};
	this.sidHashMap["Session2_MBD_Factorial:32"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/In2"] = {sid: "Session2_MBD_Factorial:33"};
	this.sidHashMap["Session2_MBD_Factorial:33"] = {rtwname: "<Root>/In2"};
	this.rtwnameHashMap["<Root>/Constant2"] = {sid: "Session2_MBD_Factorial:34"};
	this.sidHashMap["Session2_MBD_Factorial:34"] = {rtwname: "<Root>/Constant2"};
	this.rtwnameHashMap["<Root>/Constant3"] = {sid: "Session2_MBD_Factorial:35"};
	this.sidHashMap["Session2_MBD_Factorial:35"] = {rtwname: "<Root>/Constant3"};
	this.rtwnameHashMap["<Root>/Display"] = {sid: "Session2_MBD_Factorial:9"};
	this.sidHashMap["Session2_MBD_Factorial:9"] = {rtwname: "<Root>/Display"};
	this.rtwnameHashMap["<Root>/While Iterator Subsystem"] = {sid: "Session2_MBD_Factorial:1"};
	this.sidHashMap["Session2_MBD_Factorial:1"] = {rtwname: "<Root>/While Iterator Subsystem"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "Session2_MBD_Factorial:8"};
	this.sidHashMap["Session2_MBD_Factorial:8"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/IC"] = {sid: "Session2_MBD_Factorial:3"};
	this.sidHashMap["Session2_MBD_Factorial:3"] = {rtwname: "<S1>/IC"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "Session2_MBD_Factorial:20"};
	this.sidHashMap["Session2_MBD_Factorial:20"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "Session2_MBD_Factorial:26"};
	this.sidHashMap["Session2_MBD_Factorial:26"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Relational Operator"] = {sid: "Session2_MBD_Factorial:19"};
	this.sidHashMap["Session2_MBD_Factorial:19"] = {rtwname: "<S1>/Relational Operator"};
	this.rtwnameHashMap["<S1>/Unit Delay"] = {sid: "Session2_MBD_Factorial:27"};
	this.sidHashMap["Session2_MBD_Factorial:27"] = {rtwname: "<S1>/Unit Delay"};
	this.rtwnameHashMap["<S1>/While Iterator"] = {sid: "Session2_MBD_Factorial:4"};
	this.sidHashMap["Session2_MBD_Factorial:4"] = {rtwname: "<S1>/While Iterator"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "Session2_MBD_Factorial:28"};
	this.sidHashMap["Session2_MBD_Factorial:28"] = {rtwname: "<S1>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
