function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "TrafficLight_MBD"};
	this.sidHashMap["TrafficLight_MBD"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "TrafficLight_MBD:1"};
	this.sidHashMap["TrafficLight_MBD:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "TrafficLight_MBD:1"};
	this.sidHashMap["TrafficLight_MBD:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Red"] = {sid: "TrafficLight_MBD:2"};
	this.sidHashMap["TrafficLight_MBD:2"] = {rtwname: "<Root>/Red"};
	this.rtwnameHashMap["<Root>/Yellow"] = {sid: "TrafficLight_MBD:3"};
	this.sidHashMap["TrafficLight_MBD:3"] = {rtwname: "<Root>/Yellow"};
	this.rtwnameHashMap["<Root>/Green"] = {sid: "TrafficLight_MBD:4"};
	this.sidHashMap["TrafficLight_MBD:4"] = {rtwname: "<Root>/Green"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "TrafficLight_MBD:1:4"};
	this.sidHashMap["TrafficLight_MBD:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "TrafficLight_MBD:1:1"};
	this.sidHashMap["TrafficLight_MBD:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "TrafficLight_MBD:1:3"};
	this.sidHashMap["TrafficLight_MBD:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "TrafficLight_MBD:1:2"};
	this.sidHashMap["TrafficLight_MBD:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "TrafficLight_MBD:1:6"};
	this.sidHashMap["TrafficLight_MBD:1:6"] = {rtwname: "<S1>:6"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "TrafficLight_MBD:1:5"};
	this.sidHashMap["TrafficLight_MBD:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:7"] = {sid: "TrafficLight_MBD:1:7"};
	this.sidHashMap["TrafficLight_MBD:1:7"] = {rtwname: "<S1>:7"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
